language: ruby
cache: bundler
sudo: false

rvm:
  - 2.5.3

jdk: 'openjdk8'

notifications:
  irc: "irc.freenode.org#ldpddev"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  chrome: stable
  apt:
    packages:
      - chromium-chromedriver

before_script:
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver

script: bundle exec rake dcv:ci
