language: ruby
cache: bundler
sudo: false

rvm:
  - 2.4.2

jdk: 'openjdk8'

notifications:
  irc: "irc.freenode.org#ldpddev"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
  
script: bundle exec rake dcv:ci
