default: &default
  lindquist:
    collection_id: 'ldpd:130509'
    layout: 'lindquist'
    short_title: 'G.E.E Lindquist'
  css:
    collection_id: 'ldpd:135833'
    layout: 'css'
    short_title: 'Community Service Society'

development: *default
test: *default
production: *default

dcv_dev: *default
dcv_test: *default
dcv_prod: *default

dcv_private_dev: *default
dcv_private_test: *default
dcv_private_prod: *default