all_environments: &all_environments
  public:
    catalog:
      layout: 'dcv'
      date_search:
        sidebar: true
        timeline: true
    durst:
      layout: 'durst'
    ifp:
      layout: 'ifp'
      show_original_file_download: true
    lindquist:
      layout: 'lindquist'
  restricted:
    ifp:
      layout: 'ifp'
    universityseminars:
      layout: 'universityseminars'
      show_original_file_download: true
    
development: *all_environments
test: *all_environments
prod: *all_environments
dcv_private_dev: *all_environments
dcv_private_test: *all_environments
dcv_private_prod: *all_environments
dcv_dev: *all_environments
dcv_test: *all_environments
dcv_prod: *all_environments